version: "3.8"

volumes:
  postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: shortyurl-django
    depends_on:
      - postgres
    env_file:
      - .envs/.env
    networks:
      - shortyurl-network
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  postgres:
    image: postgres:14.3-alpine
    container_name: shortyurl-postgres
    env_file:
      - .envs/.env
    networks:
      - shortyurl-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  shortyurl-network:
